---
# vim:ff=unix ts=2 sw=2 ai expandtab ft=ansible:
- hosts: all
  vars:
    php_process_user: www-data
    php_process_group: www-data
    apt_file_dir: /etc/apt/sources.list.d/
    jenkins_host: localhost
  remote_user: petyo
  sudo: yes
  tasks:
    - include: a/ruby.yml
    - include: a/nginx.yml
    - include: a/google-chrome.yml
    - include: a/node.yml
    - include: a/java.yml
    - name: jenkins
      include: a/jenkins/main.yml
    - include: a/mono.yml
    - apt: name=xvfb
    - apt: name=xauth
    - include: a/php-fpm.yml	    
  handlers:
    - service: name=php5-fpm state=restarted
