---
# vim:ff=unix ts=2 sw=2 ai expandtab ft=ansible:
- hosts: all
  vars:
    php_process_user: www-data
    php_process_group: www-data
    apt_file_dir: /etc/apt/sources.list.d/
  remote_user: petyo
  sudo: yes
  tasks:
    - include: a/ruby.yml
    - include: a/nginx.yml
    - include: a/google-chrome.yml
    - include: a/node.yml
    - include: a/java.yml
    - include: a/mono.yml
    - apt: name=xvfb
    - apt: name=xauth
    - name: Install PHP
      apt: name={{item}} state=latest
      with_items:
        - php5-cli
        - php5-fpm
        - php5-gd
        - php5-sqlite
        - php5-json
    - name: Configure FPM
      template: src=a/fpm-www.conf.j2 dest=/etc/php5/fpm/pool.d/www.conf
      notify:
        - restart php5-fpm
    - service: name=php5-fpm state=started enabled=yes
  handlers:
    - service: name=php5-fpm state=restarted
